name: Download iPAs from 34306

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Download
    steps:
        name: Download
        uses: robinraju/release-downloader@v1.6
          with: 
            # The source repository path.
            # Expected format {owner}/{repo}
            # Default: ${{ github.repository }}
            repository: "34306/TrollStoreiPA"
            
            # A flag to set the download target as latest release
            # The default value is 'false'
            latest: true
            
            # The github tag. e.g: v1.0.1
            # Download assets from a specific tag/version
            # tag: ""
            
            # The name of the file to download.
            # Use this field only to specify filenames other than tarball or zipball, if any.
            # Supports wildcard pattern (eg: '*', '*.deb', '*.zip' etc..)
            fileName: "*.ipa"
            
            # Download the attached tarball (*.tar.gz)
            tarBall: true
            
            # Download the attached zipball (*.zip)
            zipBall: true
            
            # Relative path under $GITHUB_WORKSPACE to place the downloaded file(s)
            # It will create the target directory automatically if not present
            # eg: out-file-path: "my-downloads" => It will create directory $GITHUB_WORKSPACE/my-downloads
            out-file-path: "my-downloads"
            
            # Github access token to download files from private repositories
            # https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
            # eg: token: ${{ secrets.MY_TOKEN }}
            # token: ""

            # The URL of the Github API, only use this input if you are using Github Enterprise
            # Default: "https://api.github.com"
            # Use http(s)://[hostname]/api/v3 to access the API for GitHub Enterprise Server
            # github-api-url: ""
