name: Download iPAs from 34306
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Download
    uses: robinraju/release-downloader@v1.6
    with:
      repository: "34306/TrollStoreiPA"
      latest: true
      fileName: "*.ipa"
      tarBall: true
      zipBall: true
      out-file-path: "my-downloads"
