name: "Download iPAs from 34306"
on:
  # Trigger manually
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup node and cache dependencies
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'

    - name: Build and test 
      shell: bash
      run: |
        npm ci
        npm run all
    
    - name: Run action
      uses: ./
      id: download-public
      with: 
        repository: "34306/TrollStoreiPA"
        tarBall: true
        zipBall: true
        out-file-path: "./test-downloads"
          
    - name: List downloaded files
      shell: bash
      run: ls -lrth test-downloads

    # - name: Test download from a private repo
    #   uses: ./
    #   id: download-private
    #   with:
    #     repository: "robinraju/release-downloader-test"
    #     latest: true
    #     fileName: "*"
    #     tarBall: true
    #     zipBall: true
    #     token: ${{ secrets.RELEASE_DOWNLOADER_TEST_TOKEN }}
    #     out-file-path: "./downloader-test"

    # - name: List downloaded files from private repo
    #   shell: bash
    #   run: ls -lrth downloader-test


    # if [ -n ${{steps.download-private.outputs.tag_name}} ]; then
    #   echo ${{steps.download-private.outputs.tag_name}}
    # else echo "Unable to read output variable from step download-private"; exit 1
    # fi
    - name: Read output variable set by previous steps
      shell: bash
      run: |
        if [ -n ${{steps.download-public.outputs.tag_name}} ]; then
          echo ${{steps.download-public.outputs.tag_name}}
        else echo "Unable to read output variable from step download-public"; exit 1
        fi


